version: '3.1'

services:

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    
  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092    
    env_file:
      - ./env-variables/kafka.env
                                
  db:
    image: postgres:12
    restart: always
    volumes:
      - ./init-databases.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 8091:5432
    env_file:
      - ./env-variables/db.env  

  adminer:
    image: adminer
    restart: always  
    ports:
      - 8090:8080
      
  messaging:
    image: kick-scooter-messaging
    depends_on:
      - db
      - kafka
    ports:
      - 8084:8080
    env_file:
      - ./env-variables/messaging.env  
      
  identity:
    image: kick-scooter-identity
    depends_on:
      - db
    ports:
      - 8080:8080
    env_file:
      - ./env-variables/identity.env
      
  payment:
    image: kick-scooter-payment
    depends_on:
      - db
    ports:
      - 8083:8080
    env_file:
      - ./env-variables/payment.env
      
  trip:
    image: kick-scooter-trip
    depends_on:
      - db
      - kafka
    ports:
      - 8082:8080
    env_file:
      - ./env-variables/trip.env 

  vehicle:
    image: kick-scooter-vehicle
    depends_on:
      - db
      - kafka
    ports:
      - 8081:8080
    env_file:
      - ./env-variables/vehicle.env

  simulator:
    image: kick-scooter-simulator
    depends_on:
      - kafka
      - vehicle
    ports:
      - 8088:8080
    env_file:
      - ./env-variables/simulator.env          
