version: '3.1'

services:

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    
  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092    
    env_file:
      - ./env/kafka.env
                                
#  db:
#    image: postgres:12
#    restart: always
#    volumes:
#      - ./init-databases.sql:/docker-entrypoint-initdb.d/init.sql
#    ports:
#      - 8091:5432
#    env_file:
#      - ./env/db.env  

#  adminer:
#    image: adminer
#    restart: always  
#    ports:
#      - 8090:8080
      
  messaging:
    image: gitlab.svagworks.me:5050/root/demo_3:messaging
    depends_on:
#      - db
      - kafka
    ports:
      - 8084:8080
    env_file:
      - ./env/messaging.env  
      
  identity:
    image: gitlab.svagworks.me:5050/root/demo_3:identity
#    depends_on:
#      - db
    ports:
      - 8080:8080
    env_file:
      - ./env/identity.env
      
  payment:
    image: gitlab.svagworks.me:5050/root/demo_3:payment
#    depends_on:
#      - db
    ports:
      - 8083:8080
    env_file:
      - ./env/payment.env
      
  trip:
    image: gitlab.svagworks.me:5050/root/demo_3:trip
    depends_on:
#      - db
      - kafka
    ports:
      - 8082:8080
    env_file:
      - ./env/trip.env 

  vehicle:
    image: gitlab.svagworks.me:5050/root/demo_3:vehicle
    depends_on:
#      - db
      - kafka
    ports:
      - 8081:8080
    env_file:
      - ./env/vehicle.env

  simulator:
    image: gitlab.svagworks.me:5050/root/demo_3:simulation
    depends_on:
      - kafka
      - vehicle
    ports:
      - 8088:8080
    env_file:
      - ./env/simulator.env          
